import {
  faCoins,
  faSackDollar,
  faScaleBalanced,
  faScaleUnbalanced,
  faVault,
  faDollar,
  faMoneyBillTransfer,
  faMoneyBill,
  faMoneyBill1Wave,
  faDollarSign,
  faSterlingSign,
  faWallet,
  faCentSign,
  faEuro,
  faCreditCard,
  faPiggyBank,
  faCashRegister,
  faHandHoldingDollar,
  faReceipt,
  faMoneyCheck,
} from "@fortawesome/free-solid-svg-icons";

export const icons = [
  faCoins,
  faSackDollar,
  faScaleBalanced,
  faScaleUnbalanced,
  faVault,
  faDollar,
  faMoneyBillTransfer,
  faMoneyBill,
  faMoneyBill1Wave,
  faDollarSign,
  faSterlingSign,
  faWallet,
  faCentSign,
  faEuro,
  faCreditCard,
  faPiggyBank,
  faCashRegister,
  faHandHoldingDollar,
  faReceipt,
  faMoneyCheck,
];
